---
title: "Diagnostics"
author: "Austin Sell"
date: "April 10, 2018"
output: html_document
---

```{r}


data <- read.csv("Data/mysterytsUW.csv")
library(RColorBrewer)
data$period <- seq(1,100,1)
num.index <- seq(1,18,1)
parts <- NULL
for (i in 1:18){
  parts[[i]] <- data[,i]
}

#null vectors
fit <- NULL
beta <- NULL
detrended <- NULL

#functions

detrend.ts <- function(ts=NULL, beta=NULL, period=NULL){
  detrend <- NULL
  for (i in 1:length(ts)){
    detrend[i] <- ts[i] - beta*period[i]
  }
  return(detrend)
}

seasonality.graph <- function(data, title){
  col <- brewer.pal(8, "Blues")

  # Gather the data (sort the number of deaths by month and year in a matrix)
  seasonality <- matrix(data,nrow=12,ncol=length(data)/12, byrow=FALSE)

  # Repeat them as many times as needed
  col <-  as.vector(t(matrix(col, nrow=length(col), ncol=ceiling(ncol(seasonality)/length(col)))))

  # Plot each year over the months
  matplot(seasonality, type="l", col=col, lty=1, xaxt="n", xlab="Month",
          main=paste0(c("Seasonality",title)))
  axis(1, at=1:12, labels=c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"))
  abline(a=0,b=0,lty="dashed")
}

#trend

for (i in 1:18){
  #raw ts
  plot(x=data$period, y=parts[[i]], type="l", ylim=range(min(parts[[i]]),max(parts[[i]])),
       main=paste0(c("Raw Time Series",num.index[i])))
  
  #acf/pacf of raw ts
  acf(parts[[i]])
  pacf(parts[[i]])
  
  #trend modeling
  fit[[i]] <- lm(parts[[i]] ~ data$period)
  beta[i] <- fit[[i]]$coefficients[2]
  
  #detrending with plot
  detrended[[i]] <- detrend.ts(ts=parts[[i]], beta[i], period=data$period)
  plot(x=data$period, y=detrended[[i]], type="l", ylim=range(min(detrended[[i]]),max(detrended[[i]])),
       main=paste0(c("Detrended Time Series",num.index[i])))
  
  #acf/pacf of detrended ts
  acf(detrended[[i]])
  pacf(detrended[[i]])
  
  #seasonality graph
  seasonality.graph(data=parts[[i]], title=num.index[i])
}

```

```{r}
# part 2
data2 <- read.csv("Data/mysterytsUW2.csv")
data2$period <- seq(1,1000,1)
parts2 <- NULL
parts2.i <- NULL
parts2.ii <- NULL


for (i in 1:5){
  parts2[[i]] <- data2[,i]
}


for (i in 1:5){
  #question i
  parts2.i[[i]] <- parts2[[i]][1:20]
  
  #raw ts
  plot(x=data2$period[1:20], y=parts2.i[[i]], type="l", ylim=range(min(parts2.i[[i]]),max(parts2.i[[i]])),
       main=paste0(c("Raw Time Series",num.index[i])),"Observations: 20")
  
  #acf/pacf
  acf(parts2.i[[i]])
  pacf(parts2.i[[i]])


  #question ii

  parts2.ii[[i]] <- parts2[[i]][1:100]
  
  #raw ts
  plot(x=data2$period[1:100], y=parts2.ii[[i]], type="l", ylim=range(min(parts2.ii[[i]]),max(parts2.ii[[i]])),
       main=paste0(c("Raw Time Series",num.index[i])), "Observations: 100")
  
  #acf/pacf
  acf(parts2.ii[[i]])
  pacf(parts2.ii[[i]])


  # question iii

  #raw ts
  plot(x=data2$period, y=parts2[[i]], type="l", ylim=range(min(parts2[[i]]),max(parts2[[i]])),
       main=paste0(c("Raw Time Series",num.index[i])), "Observations: 1000")
  
  #acf/pacf
  acf(parts2[[i]])
  pacf(parts2[[i]])
}
```